export let keys = [
  {
    key: '`',
    keyRu: 'ё',
    keyCode: 192,
    which: 192,
    code: 'Backquote',
    location: 0,
    description: 'Backtick / grave accent / ñ / æ / ö',
  },
  {
    key: '1',
    keyRu: '1',
    keyCode: 49,
    which: 49,
    code: 'Digit1',
    location: 0,
    description: '1 Key',
    unicode: '①',
  },
  {
    key: '2',
    keyRu: '2',
    keyCode: 50,
    which: 50,
    code: 'Digit2',
    location: 0,
    description: '2 Key',
    unicode: '②',
  },
  {
    key: '3',
    keyRu: '3',
    keyCode: 51,
    which: 51,
    code: 'Digit3',
    location: 0,
    description: '3 Key',
    unicode: '③',
  },
  {
    key: '4',
    keyRu: '4',
    keyCode: 52,
    which: 52,
    code: 'Digit4',
    location: 0,
    description: '4 Key',
    unicode: '④',
  },
  {
    key: '5',
    keyRu: '5',
    keyCode: 53,
    which: 53,
    code: 'Digit5',
    location: 0,
    description: '5 Key',
    unicode: '⑤',
  },
  {
    key: '6',
    keyRu: '6',
    keyCode: 54,
    which: 54,
    code: 'Digit6',
    location: 0,
    description: '6 Key',
    unicode: '⑥',
  },
  {
    key: '7',
    keyRu: '7',
    keyCode: 55,
    which: 55,
    code: 'Digit7',
    location: 0,
    description: '7 Key',
    unicode: '⑦',
  },
  {
    key: '8',
    keyRu: '8',
    keyCode: 56,
    which: 56,
    code: 'Digit8',
    location: 0,
    description: '8 Key',
    unicode: '⑧',
  },
  {
    key: '9',
    keyRu: '9',
    keyCode: 57,
    which: 57,
    code: 'Digit9',
    location: 0,
    description: '9 Key',
    unicode: '⑨',
  },
  {
    key: '0',
    keyRu: '0',
    keyCode: 48,
    which: 48,
    code: 'Digit0',
    location: 0,
    description: '0',
    unicode: '⓪',
  },
  {
    key: '-',
    keyRu: '-',
    keyCode: 109,
    which: 109,
    code: 'NumpadSubtract',
    location: 3,
    description: 'subtract',
  },
  {
    key: '=',
    keyRu: '=',
    keyCode: 61,
    which: 61,
    code: 'Equal',
    location: 0,
    description: 'equals (firefox)',
  },
  {
    key: 'Backspace',
    keyRu: 'Backspace',
    keyCode: 8,
    which: 8,
    code: 'Backspace',
    location: 0,
    description: 'backspace / delete',
    unicode: '⌫',
  },
  {
    key: 'Tab',
    keyRu: 'Tab',
    keyCode: 9,
    which: 9,
    code: 'Tab',
    location: 0,
    description: 'tab',
    unicode: '↹',
  },
  {
    key: 'q',
    keyRu: 'й',
    keyCode: 81,
    which: 81,
    code: 'KeyQ',
    location: 0,
    description: 'q',
  },
  {
    key: 'w',
    keyRu: 'ц',
    keyCode: 87,
    which: 87,
    code: 'KeyW',
    location: 0,
    description: 'w',
  },
  {
    key: 'e',
    keyRu: 'у',
    keyCode: 69,
    which: 69,
    code: 'KeyE',
    location: 0,
    description: 'e',
  },
  {
    key: 'r',
    keyRu: 'к',
    keyCode: 82,
    which: 82,
    code: 'KeyR',
    location: 0,
    description: 'r',
  },
  {
    key: 't',
    keyRu: 'е',
    keyCode: 84,
    which: 84,
    code: 'KeyT',
    location: 0,
    description: 't',
  },
  {
    key: 'y',
    keyRu: 'н',
    keyCode: 89,
    which: 89,
    code: 'KeyY',
    location: 0,
    description: 'y',
  },
  {
    key: 'u',
    keyRu: 'г',
    keyCode: 85,
    which: 85,
    code: 'KeyU',
    location: 0,
    description: 'u',
  },
  {
    key: 'i',
    keyRu: 'ш',
    keyCode: 73,
    which: 73,
    code: 'KeyI',
    location: 0,
    description: 'i',
  },
  {
    key: 'o',
    keyRu: 'щ',
    keyCode: 79,
    which: 79,
    code: 'KeyO',
    location: 0,
    description: 'o',
  },
  {
    key: 'p',
    keyRu: 'з',
    keyCode: 80,
    which: 80,
    code: 'KeyP',
    location: 0,
    description: 'p',
  },
  {
    key: '[',
    keyRu: 'х',
    keyCode: 160,
    which: 160,
    code: 'BracketLeft',
    location: 0,
    altKey: false,
    ctrlKey: false,
    metaKey: false,
    shiftKey: false,
    description: '^',
  },
  {
    key: ']',
    keyRu: 'ъ',
    keyCode: 221,
    which: 221,
    code: 'BracketRight',
    location: 0,
    description: 'close bracket / å',
  },
  {
    key: 'Delete',
    keyRu: 'Delete',
    keyCode: 46,
    which: 46,
    code: 'NumpadDecimal',
    location: 3,
    altKey: false,
    ctrlKey: false,
    metaKey: false,
    shiftKey: false,
    description: 'delete',
    unicode: '⌦',
  },
  {
    key: 'CapsLock',
    keyRu: 'CapsLock',
    keyCode: 20,
    which: 20,
    code: 'CapsLock',
    location: 0,
    description: 'caps lock',
    unicode: '⇪',
  },
  {
    key: 'a',
    keyRu: 'ф',
    keyCode: 65,
    which: 65,
    code: 'KeyA',
    location: 0,
    description: 'a',
  },
  {
    key: 's',
    keyRu: 'ы',
    keyCode: 83,
    which: 83,
    code: 'KeyS',
    location: 0,
    description: 's',
  },
  {
    key: 'd',
    keyRu: 'в',
    keyCode: 68,
    which: 68,
    code: 'KeyD',
    location: 0,
    description: 'd',
  },
  {
    key: 'f',
    keyRu: 'а',
    keyCode: 70,
    which: 70,
    code: 'KeyF',
    location: 0,
    description: 'f',
  },
  {
    key: 'g',
    keyRu: 'п',
    keyCode: 71,
    which: 71,
    code: 'KeyG',
    location: 0,
    description: 'g',
  },
  {
    key: 'h',
    keyRu: 'р',
    keyCode: 72,
    which: 72,
    code: 'KeyH',
    location: 0,
    description: 'h',
  },
  {
    key: 'j',
    keyRu: 'о',
    keyCode: 74,
    which: 74,
    code: 'KeyJ',
    location: 0,
    description: 'j',
  },
  {
    key: 'k',
    keyRu: 'л',
    keyCode: 75,
    which: 75,
    code: 'KeyK',
    location: 0,
    altKey: true,
    ctrlKey: false,
    metaKey: true,
    shiftKey: false,
    description: 'k',
  },
  {
    key: 'l',
    keyRu: 'д',
    keyCode: 76,
    which: 76,
    code: 'KeyL',
    location: 0,
    altKey: true,
    ctrlKey: false,
    metaKey: true,
    shiftKey: false,
    description: 'l',
  },
  {
    key: ';',
    keyRu: 'ж',
    keyCode: 59,
    which: 59,
    code: 'Semicolon',
    location: 0,
    description: 'semicolon (firefox), equals',
  },
  {
    key: "'",
    keyRu: 'э',
    keyCode: 222,
    which: 222,
    code: 'Quote',
    location: 0,
    description: 'single quote / ø / ä',
  },
  {
    key: '\\',
    keyRu: '\\',
    keyCode: 220,
    which: 220,
    code: 'Backslash',
    location: 0,
    description: 'back slash',
  },
  {
    key: 'Enter',
    keyRu: 'Enter',
    keyCode: 13,
    which: 13,
    code: 'Enter',
    location: 0,
    description: 'Enter / Return',
    unicode: '↵',
  },
  {
    key: 'Shift',
    keyRu: 'Shift',
    keyCode: 16,
    which: 16,
    code: 'ShiftLeft',
    location: 1,
    description: 'shift',
    unicode: '⇧',
  },
  {
    key: 'z',
    keyRu: 'я',
    keyCode: 90,
    which: 90,
    code: 'KeyZ',
    location: 0,
    description: 'z',
  },
  {
    key: 'x',
    keyRu: 'ч',
    keyCode: 88,
    which: 88,
    code: 'KeyX',
    location: 0,
    description: 'x',
  },
  {
    key: 'c',
    keyRu: 'с',
    keyCode: 67,
    which: 67,
    code: 'KeyC',
    location: 0,
    description: 'c',
  },
  {
    key: 'v',
    keyRu: 'м',
    keyCode: 86,
    which: 86,
    code: 'KeyV',
    location: 0,
    description: 'v',
  },
  {
    key: 'b',
    keyRu: 'и',
    keyCode: 66,
    which: 66,
    code: 'KeyB',
    location: 0,
    description: 'b',
  },
  {
    key: 'n',
    keyRu: 'т',
    keyCode: 78,
    which: 78,
    code: 'KeyN',
    location: 0,
    description: 'n',
  },
  {
    key: 'm',
    keyRu: 'ь',
    keyCode: 77,
    which: 77,
    code: 'KeyM',
    location: 0,
    description: 'm',
  },
  {
    key: ',',
    keyRu: 'б',
    keyCode: 188,
    which: 188,
    code: 'Comma',
    location: 3,
    altKey: false,
    ctrlKey: false,
    metaKey: false,
    shiftKey: false,
    description: 'numpad period (firefox)',
  },
  {
    key: '.',
    keyRu: 'ю',
    keyCode: 190,
    which: 190,
    code: 'Period',
    location: 0,
    description: 'period',
  },
  {
    key: '/',
    keyRu: '.',
    keyCode: 191,
    which: 191,
    code: 'Slash',
    location: 0,
    description: 'forward slash / ç',
  },
  {
    key: '↑',
    keyRu: '↑',
    keyCode: 38,
    which: 38,
    code: 'ArrowUp',
    location: 0,
    altKey: false,
    ctrlKey: false,
    metaKey: false,
    shiftKey: false,
    repeat: false,
  },
  {
    key: 'Shift',
    keyRu: 'Shift',
    keyCode: 16,
    which: 16,
    code: 'ShiftRight',
    location: 2,
    description: 'shift',
    unicode: '⇧',
  },
  {
    key: 'Ctrl',
    keyRu: 'Ctrl',
    keyCode: 17,
    which: 17,
    code: 'ControlLeft',
    location: 1,
    altKey: true,
    ctrlKey: false,
    metaKey: true,
    shiftKey: true,
    description: 'ctrl',
    unicode: '^',
  },
  {
    key: 'Win',
    keyRu: 'Win',
    keyCode: 91,
    which: 91,
    code: 'MetaLeft',
    location: 1,
    altKey: false,
    ctrlKey: false,
    metaKey: true,
    shiftKey: false,
    description: 'Windows Key / Left ⌘ / Chromebook Search key',
    unicode: '⌘ ⊞',
  },
  {
    key: 'Alt',
    keyRu: 'Alt',
    keyCode: 18,
    which: 18,
    code: 'AltLeft',
    location: 1,
    altKey: true,
    ctrlKey: false,
    metaKey: true,
    shiftKey: false,
    description: 'Alt / Option',
    unicode: '⎇ / ⌥',
  },
  {
    key: ' ',
    keyRu: ' ',
    keyCode: 32,
    which: 32,
    code: 'Space',
    location: 0,
    altKey: false,
    ctrlKey: false,
    metaKey: false,
    shiftKey: false,
    repeat: false,
  },
  {
    key: 'Alt',
    keyRu: 'Alt',
    keyCode: 18,
    which: 18,
    code: 'AltRight',
    location: 2,
    altKey: true,
    ctrlKey: false,
    metaKey: true,
    shiftKey: false,
    description: 'Alt / Option',
    unicode: '⎇ / ⌥',
  },
  {
    key: '←',
    keyRu: '←',
    keyCode: 37,
    which: 37,
    code: 'ArrowLeft',
    location: 0,
    altKey: false,
    ctrlKey: false,
    metaKey: false,
    shiftKey: false,
    repeat: false,
  },
  {
    key: '↓',
    keyRu: '↓',
    keyCode: 40,
    which: 40,
    code: 'ArrowDown',
    location: 0,
    altKey: false,
    ctrlKey: false,
    metaKey: false,
    shiftKey: false,
    repeat: false,
  },
  {
    key: '→',
    keyRu: '→',
    keyCode: 39,
    which: 39,
    code: 'ArrowRight',
    location: 0,
    altKey: false,
    ctrlKey: false,
    metaKey: false,
    shiftKey: false,
    repeat: false,
  },
  {
    key: 'Ctrl',
    keyRu: 'Ctrl',
    keyCode: 17,
    which: 17,
    code: 'ControlRight',
    location: 1,
    altKey: true,
    ctrlKey: false,
    metaKey: true,
    shiftKey: true,
    description: 'ctrl',
    unicode: '^',
  },
];
